### ISSUE TITLE
The function of Audio-Jack3 ?

### ISSUE THREAD

**Issue by liangzhaoliang95** [Galzai/MK32#12]
The function of Audio-Jack3 ? 
we can use ESP-NOW to connect two pads

**Comment by Galzai** [comment]
It's there just in case you'd want to add more i2c functionally to enable easy testing (the board is intended for testing).

**Comment by liangzhaoliang95** [comment]
i think if you can supply a whole hardware project(include a build-log)
this will help many many person like me who has not enough hardware skill,
it will be very nice
