### ISSUE TITLE
define LAYERS  cannot set 2

### ISSUE THREAD

**Issue by lovesugarxyz** [Galzai/MK32#18]
cannot set #define LAYERS 2
detail:

CC build/main/components/u8g2_OLED/u8x8_d_ks0108.o
CC build/main/components/u8g2_OLED/u8log.o
CC build/main/components/u8g2_OLED/u8x8_d_st75256.o
CC build/main/components/u8g2_OLED/u8g2_kerning.o
CC build/main/components/u8g2_OLED/u8x8_d_pcd8544_84x48.o
CC build/main/components/u8g2_OLED/u8x8_d_ssd1607_200x200.o
CC build/main/components/u8g2_OLED/u8x8_display.o
CC build/main/components/u8g2_OLED/u8x8_byte.o
CC build/main/components/u8g2_OLED/u8x8_d_ssd1305.o
CC build/main/components/r_encoder/r_encoder.o
CC build/main/components/espnow/espnow_recieve.o
In file included from /home/runner/esp/MK32/components/espnow/espnow_recieve.c:30:
/home/runner/esp/esp-idf/components/esp_event/include/esp_event_loop.h:2:2: warning: #warning "esp_event_loop.h is deprecated, please include esp_event.h instead" [-Wcpp]
 #warning "esp_event_loop.h is deprecated, please include esp_event.h instead"
  ^~~~~~~
In file included from /home/runner/esp/MK32/components/espnow/espnow_recieve.c:31:
/home/runner/esp/esp-idf/components/tcpip_adapter/include/tcpip_adapter.h:15:2: warning: #warning "This header is deprecated, please use new network related API in esp_netif.h" [-Wcpp]
 #warning "This header is deprecated, please use new network related API in esp_netif.h"
  ^~~~~~~
/home/runner/esp/MK32/components/espnow/espnow_recieve.c: In function 'wifi_initialize_recieve':
/home/runner/esp/MK32/components/espnow/espnow_recieve.c:55:2: warning: 'tcpip_adapter_init' is deprecated [-Wdeprecated-declarations]
  tcpip_adapter_init();
  ^~~~~~~~~~~~~~~~~~
In file included from /home/runner/esp/esp-idf/components/esp_netif/include/esp_netif.h:35,
                 from /home/runner/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:22,
                 from /home/runner/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /home/runner/esp/esp-idf/components/esp_event/include/esp_event_loop.h:3,
                 from /home/runner/esp/MK32/components/espnow/espnow_recieve.c:30:
/home/runner/esp/esp-idf/components/tcpip_adapter/include/tcpip_adapter.h:34:6: note: declared here
 void tcpip_adapter_init(void)  __attribute__ ((deprecated));
      ^~~~~~~~~~~~~~~~~~
CC build/main/components/espnow/espnow_send.o
In file included from /home/runner/esp/MK32/components/espnow/espnow_send.c:29:
/home/runner/esp/esp-idf/components/esp_event/include/esp_event_loop.h:2:2: warning: #warning "esp_event_loop.h is deprecated, please include esp_event.h instead" [-Wcpp]
 #warning "esp_event_loop.h is deprecated, please include esp_event.h instead"
  ^~~~~~~
In file included from /home/runner/esp/MK32/components/espnow/espnow_send.c:30:
/home/runner/esp/esp-idf/components/tcpip_adapter/include/tcpip_adapter.h:15:2: warning: #warning "This header is deprecated, please use new network related API in esp_netif.h" [-Wcpp]
 #warning "This header is deprecated, please use new network related API in esp_netif.h"
  ^~~~~~~
/home/runner/esp/MK32/components/espnow/espnow_send.c: In function 'wifi_initialize_send':
/home/runner/esp/MK32/components/espnow/espnow_send.c:62:2: warning: 'tcpip_adapter_init' is deprecated [-Wdeprecated-declarations]
  tcpip_adapter_init();
  ^~~~~~~~~~~~~~~~~~
In file included from /home/runner/esp/esp-idf/components/esp_netif/include/esp_netif.h:35,
                 from /home/runner/esp/esp-idf/components/esp_event/include/esp_event_legacy.h:22,
                 from /home/runner/esp/esp-idf/components/esp_event/include/esp_event.h:26,
                 from /home/runner/esp/esp-idf/components/esp_event/include/esp_event_loop.h:3,
                 from /home/runner/esp/MK32/components/espnow/espnow_send.c:29:
/home/runner/esp/esp-idf/components/tcpip_adapter/include/tcpip_adapter.h:34:6: note: declared here
 void tcpip_adapter_init(void)  __attribute__ ((deprecated));
      ^~~~~~~~~~~~~~~~~~
CC build/main/components/ble_new/hid_device_le_prf.o
CC build/main/components/ble_new/hal_ble.o
CC build/main/components/ble_new/keyboard.o
CC build/main/components/ble_new/hid_dev.o
CXX build/main/mk32_main.o
In file included from /home/runner/esp/MK32/main/mk32_main.cpp:30:
/home/runner/esp/esp-idf/components/esp_event/include/esp_event_loop.h:2:2: warning: #warning "esp_event_loop.h is deprecated, please include esp_event.h instead" [-Wcpp]
 #warning "esp_event_loop.h is deprecated, please include esp_event.h instead"
  ^~~~~~~
In file included from /home/runner/esp/MK32/plugins/plugin_components/wifi_manager/wifi_manager.h:12,
                 from /home/runner/esp/MK32/plugins/plugin_manager.h:16,
                 from /home/runner/esp/MK32/plugins/plugins.h:14,
                 from /home/runner/esp/MK32/main/keymap.c:7,
                 from /home/runner/esp/MK32/main/keypress_handles.c:25,
                 from /home/runner/esp/MK32/main/mk32_main.cpp:48:
/home/runner/esp/esp-idf/components/tcpip_adapter/include/tcpip_adapter.h:15:2: warning: #warning "This header is deprecated, please use new network related API in esp_netif.h" [-Wcpp]
 #warning "This header is deprecated, please use new network related API in esp_netif.h"
  ^~~~~~~
In file included from /home/runner/esp/MK32/main/keypress_handles.c:25,
                 from /home/runner/esp/MK32/main/mk32_main.cpp:48:
/home/runner/esp/MK32/main/keymap.c:28:3: error: too many initializers for 'char [2][15]'
   };
   ^
/home/runner/esp/MK32/main/keymap.c:58:55: error: too many initializers for 'uint16_t [2][4]' {aka 'short unsigned int [2][4]'}
   { MOUSE_ENCODER, KC_MS_UP, KC_MS_DOWN, KC_MS_BTN1 } };
                                                       ^
/home/runner/esp/MK32/main/keymap.c:66:58: error: too many initializers for 'uint16_t [2][4]' {aka 'short unsigned int [2][4]'}
   { MOUSE_ENCODER, KC_MS_RIGHT, KC_MS_LEFT, KC_MS_BTN2 } };
                                                          ^
make[1]: *** [mk32_main.o] Error 1
/home/runner/esp/esp-idf/make/component_wrapper.mk:291: recipe for target 'mk32_main.o' failed
make: *** [component-main-build] Error 2
/home/runner/esp/esp-idf/make/project.mk:635: recipe for target 'component-main-build' failed
Error: Process completed with exit code 2.

**Comment by Galzai** [comment]
I think you need to erase the extra mappings in keymap.c (for encoders for example)
