### ISSUE TITLE
error in cmakelist esp-idf4.2_py3.8_env w10

### ISSUE THREAD

**Issue by Algora484** [Galzai/MK32#21]
![Captura de pantalla 2021-02-09 161153](https://user-images.githubusercontent.com/19543054/107429553-0d239e00-6af2-11eb-83f4-333129ed6179.png)
![Captura de pantalla 2021-02-09 161510](https://user-images.githubusercontent.com/19543054/107429554-0dbc3480-6af2-11eb-8662-d7637b143e38.png)

I can´t compile to build or flash

**Comment by Galzai** [comment]
Hi,
This repository hasn't been updated since esp-idf 4.0.
You can use esp-idf 4.0 and follow the instructions here: https://github.com/Galzai/MK32/wiki/Building-and-flashing 

Hope this helps
