### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by 1787900577** [Galzai/MK32#22]
D:/mysy3201/msys32/home/yxx/esp/mk32/components/ble_new/hid_device_le_prf.c:275:22: error: 'char_prop_read_write_notify' defined but not used [-Werror=unused-const-variable=]
 static const uint8_t char_prop_read_write_notify = ESP_GATT_CHAR_PROP_BIT_READ
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/mysy3201/msys32/home/yxx/esp/mk32/components/ble_new/hid_device_le_prf.c:268:22: error: 'char_prop_notify' defined but not used [-Werror=unused-const-variable=]
 static const uint8_t char_prop_notify = ESP_GATT_CHAR_PROP_BIT_NOTIFY;
                      ^~~~~~~~~~~~~~~~
cc1.exe: some warnings being treated as errors
make[1]: *** [/home/yxx/esp/esp-idf-v4.0/make/component_wrapper.mk:292：components/ble_new/hid_device_le_prf.o] error 1
make: *** [D:\mysy3201\msys32\home\yxx\esp\esp-idf-v4.0/make/project.mk:590：component-main-build] error 2

**Comment by gijsneerhof** [comment]
You can comment these lines, they're defined twice in the file
