### ISSUE TITLE
Flash Trouble

### ISSUE THREAD

**Issue by Lingyi0601** [Galzai/MK32#27]
Hello!
    I hava some problem about the process of flashing,such as how flash it without cmakelist, and could tell me your flash steps by more details,thank you;
 I'm looking forward to your reply!

**Comment by Lingyi0601** [comment]
could you provide a process with details to my email? I'm very insterted in it,but it's ok if you don't,thanks.

**Comment by Galzai** [comment]
https://github.com/Galzai/MK32/wiki/Building-and-flashing

Note that you need to use esp-idf v4.0

**Comment by Lingyi0601** [comment]
Thank you,I'll try it.

**Comment by Lingyi0601** [comment]
Is it because you are using Linux OS?
