### ISSUE TITLE
Many buttons doesn't work on android

### ISSUE THREAD

**Issue by vipaoL** [Galzai/MK32#43]
I tested the keyboard with my linux PC and it works perfectly but on android some buttons just don't do anything: not even the screen wakes up, although LED on my ESP blinks when i press the button, which doesn't work. This problem shows up with all my android devices

**Comment by vipaoL** [comment]
![image](https://user-images.githubusercontent.com/59665125/183041438-59311269-22d9-4dee-a308-6d9581c16989.png)

**Comment by vipaoL** [comment]
I also found that it doesn't work at all with postmarketOS (galaxy s3) although pairing and connecting work

**Comment by Galzai** [comment]
If I remember correctly you can undefine the `NKRO `Macro in `keyboard_config.h` to get it to work on Android as well.

**Comment by vipaoL** [comment]
Thank you!!!
