### ISSUE TITLE
What's the expected battery life for different batteries?

### ISSUE THREAD

**Issue by Na-Cly** [Galzai/MK32#9]
What kind of battery life do you see when using a 3.7v lipo and any other information you have?

Thanks.

**Comment by Galzai** [comment]
You can see the amperage measurements I got here:
https://github.com/Galzai/MK32/wiki/Power-Management 
the bottom line is though that the ESP32 isn't very power efficient, you could get around a day of use with deep sleep enabled and an 1000mah battery.
